/*
* Abstract method defines
*/

void drawMessage(char*);
void firstStart();
void startAltClockline(bool sdStart = false);
void endAltClockline();
bool tempLimits();
float calFunction(uint16_t rawValue);
void createThermalImg(bool menu = false);
void floatToChar(char* buffer, float val);
void showSpot();
void showColorBar();
void settingsMenu();
void timeMenu(bool firstStart = false);
void dateMenu(bool firstStart = false);
void limitValues();
void timeAndDateMenu(bool firstStart = false);
void saveRawData(bool image, char* name, uint16_t framesCaptured = 0);
void proccessVideoFrames(uint16_t framesCaptured, char* dirname);
void createVideoFolder(char* dirname);
void buttonIRQ();
void touchIRQ();
void fillImageArray();
void gaussianBlur(unsigned short *img, long width, long height, float sigma,
	int numsteps);
void convertColors();
void scaleValues();
void bootScreen();
void storageMenu();
float bytesToFloat(uint8_t* farray);
float celciusToFahrenheit(float Tc);
void frameFilename(char* filename, uint16_t count);
void liveMode();
void loadThermal();
void loadRawData(char* filename, char* dirname = NULL);
void settingsMenuHandler();
void connectionMenu();
void connectionMenuHandler();
void saveThermalImage(char* filename, char* dirname = NULL);
uint16_t getVideoFrameNumber(char* dirname);
bool checkSDCard();
void getTemperatures(bool save = false);
void liveModeHelper();
void selectColorScheme();
void changeColorScheme(byte* pos);
void calibrationProcess();
void clearTemperatures();
void tempPointFunction(bool remove = false);
void displayThermalImg();
void showTemperatures();
bool calibrate();
void changeDisplayOptions(byte* pos);
void displayInfos();
void detachInterrupts();
void attachInterrupts();
void limitLock();
void showMsg(char* msg, bool bottom = false);
void createJPGFile(char* filename, char* dirname = NULL);